version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
      - mkdir artifact/marwan-sean_p1_api-1.0-SNAPSHOT.war
      - unzip target/ -d artifact/
      - pwd
      - ls -al
artifacts:
  files:
    - artifact/**/*
  name: artifact