version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - aws s3 cp s3://marwan-sean-school-api-files/application.properties ./src/main/resources/application.properties
  build:
    commands:
      - echo Build started on `date`
      - mvn package
      - mv target/*.war ./school.war
  post_build:
    commands:
      - echo Build completed on `date`
      - unzip school.war -d artifact/
      - pwd
      - ls -al
artifacts:
  files:
    - WEB-INF/**/*
  name: artifact